name: Simple Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Create config.js
      run: |
        cat > config.js << EOF
        window.firebaseConfig = {
          apiKey: "${{ secrets.FIREBASE_API_KEY }}",
          authDomain: "${{ secrets.FIREBASE_AUTH_DOMAIN }}",
          projectId: "${{ secrets.FIREBASE_PROJECT_ID }}",
          storageBucket: "${{ secrets.FIREBASE_STORAGE_BUCKET }}",
          messagingSenderId: "${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}",
          appId: "${{ secrets.FIREBASE_APP_ID }}"
        };
        EOF
        
    - name: Commit and push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add config.js
        git commit -m "Update config.js with secrets" || exit 0
        git push
