name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build with environment variables
      run: |
        # 환경변수를 config.js 파일로 생성
        cat > config.js << EOF
        // GitHub Actions에서 생성된 설정 파일
        window.firebaseConfig = {
          apiKey: "${{ secrets.FIREBASE_API_KEY }}",
          authDomain: "${{ secrets.FIREBASE_AUTH_DOMAIN }}",
          projectId: "${{ secrets.FIREBASE_PROJECT_ID }}",
          storageBucket: "${{ secrets.FIREBASE_STORAGE_BUCKET }}",
          messagingSenderId: "${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}",
          appId: "${{ secrets.FIREBASE_APP_ID }}"
        };
        EOF
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
